# Generated by Django 3.2 on 2025-01-16 09:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('credentials', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arrival_date', models.DateTimeField()),
                ('departure_date', models.DateTimeField()),
                ('services', models.CharField(choices=[('Boarding', 'Boarding'), ('Daycare', 'Daycare'), ('Grooming', 'Grooming'), ('Nutrition', 'Nutrition'), ('Veterinary', 'Veterinary')], max_length=50)),
                ('pet_name', models.CharField(max_length=40)),
                ('pet_type', models.CharField(choices=[('Dog', 'Dog'), ('Cat', 'Cat')], max_length=10)),
                ('breed', models.CharField(max_length=40)),
                ('age', models.PositiveBigIntegerField()),
                ('weight', models.PositiveIntegerField()),
                ('sex', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('description', models.TextField()),
                ('status', models.BooleanField(default=False)),
                ('payment_status', models.BooleanField(default=False)),
                ('doctor', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='credentials.doctor')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PetLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pet', models.CharField(max_length=250)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Treating', 'Treating'), ('All Done', 'All Done'), ('Released', 'Released')], default='Released', max_length=50, null=True)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='credentials.customer')),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='credentials.doctor')),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='daycare.booking')),
                ('pet_log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='daycare.petlog')),
            ],
        ),
    ]
