# Generated by Django 5.1.2 on 2025-02-25 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daycare', '0002_booking_rate_alter_booking_pet_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='rate',
        ),
        migrations.AlterField(
            model_name='booking',
            name='pet_type',
            field=models.CharField(choices=[('Dog', 'Dog'), ('Cat', 'Cat')], max_length=10),
        ),
        migrations.AlterField(
            model_name='booking',
            name='sex',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10),
        ),
    ]
